"""Backtest models - request and response models for backtest endpoints."""

from .requests import (
    BacktestVersion,
    Broker,
    ApplySubscription,
    SymphonyDefinition,
    BacktestRequest,
    BacktestExistingSymphonyRequest,
    Quote,
    SymphonyRebalanceState,
    RebalanceRequest,
)
from .responses import (
    Costs,
    DataWarning,
    LegendEntry,
    BacktestResult,
    RecommendedTrade,
    SymphonyRunResult,
    RebalanceResult,
    ConfigKey,
    ConstantsConfig,
    DepositPresetsConfig,
    OpenAIPromptConfig,
    OpenAIConfig,
    ConfigEntry,
    Modification,
    ScoreExtendedResponse,
)
from .symphony import (
    # Enums
    ParameterType,
    AssetClass,
    # Models
    IndicatorParameter,
    Indicator,
    SymphonyMeta,
    SymphonyMetaResponse,
    SymphonyDetail,
    SymphonyVersionInfo,
    TickersResponse,
    AISymphonyDescription,
    UserSymphony,
    DraftSymphony,
    WatchlistSymphony,
    WatchlistSymphonyItem,
    UserSymphoniesResponse,
    DraftSymphoniesResponse,
    WatchlistResponse,
    SymphonyTickersResponse,
    ModifySymphonyResponse,
    FindAndReplaceOperation,
    CompressNestedIfsModification,
    BulkModifySymphoniesRequest,
    UpdateSymphonyResponse,
    UpdateSymphonyNodesResponse,
)

__all__ = [
    # Enums - Backtest
    "BacktestVersion",
    "Broker",
    "ApplySubscription",
    # Enums - Symphony
    "ParameterType",
    "AssetClass",
    # Symphony models
    "IndicatorParameter",
    "Indicator",
    "SymphonyMeta",
    "SymphonyMetaResponse",
    "SymphonyDetail",
    "SymphonyVersionInfo",
    "TickersResponse",
    "AISymphonyDescription",
    "UserSymphony",
    "DraftSymphony",
    "WatchlistSymphony",
    "WatchlistSymphonyItem",
    "UserSymphoniesResponse",
    "DraftSymphoniesResponse",
    "WatchlistResponse",
    "SymphonyTickersResponse",
    "ModifySymphonyResponse",
    "FindAndReplaceOperation",
    "CompressNestedIfsModification",
    "BulkModifySymphoniesRequest",
    "UpdateSymphonyResponse",
    "UpdateSymphonyNodesResponse",
    # Response models
    "Modification",
    "ScoreExtendedResponse",
    # Symphony models (old backtest)
    "SymphonyDefinition",
    # Request models
    "BacktestRequest",
    "BacktestExistingSymphonyRequest",
    "Quote",
    "SymphonyRebalanceState",
    "RebalanceRequest",
    # Response models
    "Costs",
    "DataWarning",
    "LegendEntry",
    "BacktestResult",
    "RecommendedTrade",
    "SymphonyRunResult",
    "RebalanceResult",
    # Config models
    "ConfigKey",
    "ConstantsConfig",
    "DepositPresetsConfig",
    "OpenAIPromptConfig",
    "OpenAIConfig",
    "ConfigEntry",
]
