"""Symphony definition for d85d1d87-696e-4c5c-9487-ce417e20f1cd"""

from composer.models.common.symphony import *
from composer import ComposerClient
from dotenv import load_dotenv
import os

load_dotenv()

symph = SymphonyDefinition(
    id="d85d1d87-696e-4c5c-9487-ce417e20f1cd",
    step="root",
    name="The Holy Grail (Invest Copy)",
    description="",
    rebalance=RebalanceFrequency.NONE,
    rebalance_corridor_width=0.05,
    children=[
        WeightCashEqual(
            id="c73e32d0-a7c1-4e7f-b46b-02cd564b9de5",
            step="wt-cash-equal",
            children=[
                If(
                    id="bf8d013a-8e85-4e70-9aab-578ccbf3774e",
                    weight=WeightMap(
                        num=100,
                        den=100,
                    ),
                    step="if",
                    children=[
                        IfChildTrue(
                            id="4050565d-1af3-4b8a-82a1-256bd490972b",
                            step="if-child",
                            is_else_condition=False,
                            comparator="gt",
                            lhs_fn=Function.CURRENT_PRICE,
                            lhs_window_days=10,
                            lhs_val="TQQQ",
                            rhs_val="TQQQ",
                            rhs_fixed_value=False,
                            rhs_fn=Function.MOVING_AVERAGE_PRICE,
                            rhs_window_days=200,
                            children=[
                                WeightCashEqual(
                                    id="14524341-4df9-429e-8259-aaf29d1256be",
                                    step="wt-cash-equal",
                                    children=[
                                        If(
                                            id="6e73848d-da6a-426b-80b8-1e9dfe5bdea3",
                                            weight=WeightMap(
                                                num="80",
                                                den=100,
                                            ),
                                            step="if",
                                            children=[
                                                IfChildTrue(
                                                    id="c00deda2-d904-4faa-ab82-669b2df37fdd",
                                                    step="if-child",
                                                    is_else_condition=False,
                                                    comparator="gt",
                                                    lhs_fn=Function.RELATIVE_STRENGTH_INDEX,
                                                    lhs_window_days=10,
                                                    lhs_val="TQQQ",
                                                    rhs_val="79",
                                                    rhs_fixed_value=True,
                                                    children=[
                                                        Asset(
                                                            id="095f3722-5840-4f8e-9228-ffde874ff17a",
                                                            step="asset",
                                                            name="ProShares Ultra VIX Short-Term Futures ETF",
                                                            ticker="UVXY",
                                                            exchange="BATS",
                                                            price=13.69,
                                                            dollar_volume=843913560.9399999,
                                                            has_marketcap=False,
                                                            children_count=0,
                                                        ),
                                                    ],
                                                ),
                                                IfChildFalse(
                                                    id="a9473584-2977-4931-bda2-cfe81e38e1fc",
                                                    step="if-child",
                                                    is_else_condition=True,
                                                    children=[
                                                        Asset(
                                                            id="f41265ed-7f43-4ef3-936c-129e14d2ae8a",
                                                            step="asset",
                                                            name="ProShares UltraPro QQQ",
                                                            ticker="TQQQ",
                                                            exchange="XNAS",
                                                            price=32.28,
                                                            dollar_volume=6438152097.4800005,
                                                            has_marketcap=False,
                                                        ),
                                                    ],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                        IfChildFalse(
                            id="41ba3797-c73d-4382-bfdb-2bd851a0a3f0",
                            step="if-child",
                            is_else_condition=True,
                            children=[
                                WeightCashEqual(
                                    id="57657dbb-d9a4-4075-9dd0-92420912e2db",
                                    step="wt-cash-equal",
                                    children=[
                                        If(
                                            id="c8086f89-6418-4561-8d84-f0537268bd37",
                                            step="if",
                                            children=[
                                                IfChildTrue(
                                                    id="29f8c588-610d-4ee7-a905-2b9a46f73e50",
                                                    step="if-child",
                                                    is_else_condition=False,
                                                    comparator="lt",
                                                    lhs_fn=Function.RELATIVE_STRENGTH_INDEX,
                                                    lhs_window_days=10,
                                                    lhs_val="TQQQ",
                                                    rhs_val="31",
                                                    rhs_fixed_value=True,
                                                    children=[
                                                        Asset(
                                                            id="5a5f2aa8-aee3-4395-9d16-6275f3e2db88",
                                                            step="asset",
                                                            name="Direxion Daily Technology Bull 3x Shares",
                                                            ticker="TECL",
                                                            exchange="ARCX",
                                                            price=31.38,
                                                            dollar_volume=155608713.0,
                                                            has_marketcap=False,
                                                        ),
                                                    ],
                                                ),
                                                IfChildFalse(
                                                    id="8652bc70-1e15-4533-9f68-abd27dc595e7",
                                                    step="if-child",
                                                    is_else_condition=True,
                                                    children=[
                                                        WeightCashEqual(
                                                            id="effabcd3-8044-4dcf-99d7-b0ce68573077",
                                                            step="wt-cash-equal",
                                                            children=[
                                                                If(
                                                                    id="60e652ab-7bba-40ca-a810-d4023c51c3d6",
                                                                    step="if",
                                                                    children=[
                                                                        IfChildTrue(
                                                                            id="23b3ff7c-d81e-4fe0-97d6-3aff06b3ed3e",
                                                                            step="if-child",
                                                                            is_else_condition=False,
                                                                            comparator="lt",
                                                                            lhs_fn=Function.RELATIVE_STRENGTH_INDEX,
                                                                            lhs_window_days=10,
                                                                            lhs_val="SOXL",
                                                                            rhs_val="30",
                                                                            rhs_fixed_value=True,
                                                                            children=[
                                                                                Asset(
                                                                                    id="6c324abc-444e-441f-a2f8-ec55cbe91668",
                                                                                    step="asset",
                                                                                    name="Direxion Daily Semiconductor Bull 3x Shares",
                                                                                    ticker="SOXL",
                                                                                    exchange="ARCX",
                                                                                    price=16.95,
                                                                                    dollar_volume=1305626803.5,
                                                                                    has_marketcap=False,
                                                                                ),
                                                                            ],
                                                                        ),
                                                                        IfChildFalse(
                                                                            id="3882c556-15ef-4d19-be71-e41dd8f42803",
                                                                            step="if-child",
                                                                            is_else_condition=True,
                                                                            children=[
                                                                                WeightCashEqual(
                                                                                    id="69a5fe8a-dd15-4bc2-9345-f269bb0c898a",
                                                                                    step="wt-cash-equal",
                                                                                    children=[
                                                                                        If(
                                                                                            id="9c86b5dd-b94e-4a8c-a950-98e8861d5d80",
                                                                                            step="if",
                                                                                            children=[
                                                                                                IfChildTrue(
                                                                                                    id="eed488d6-096e-4905-88a0-761d820bc41a",
                                                                                                    step="if-child",
                                                                                                    is_else_condition=False,
                                                                                                    comparator="lt",
                                                                                                    lhs_fn=Function.CURRENT_PRICE,
                                                                                                    lhs_val="TQQQ",
                                                                                                    rhs_val="TQQQ",
                                                                                                    rhs_fn=Function.MOVING_AVERAGE_PRICE,
                                                                                                    rhs_window_days=20,
                                                                                                    children=[
                                                                                                        WeightCashEqual(
                                                                                                            id="ce12b496-f839-41aa-9856-85de001d50a3",
                                                                                                            step="wt-cash-equal",
                                                                                                            children=[
                                                                                                                Filter(
                                                                                                                    id="87454350-d2e7-451f-867f-c3c4316805f2",
                                                                                                                    step="filter",
                                                                                                                    select_=True,
                                                                                                                    select_fn="top",
                                                                                                                    select_n=1,
                                                                                                                    sort_by_=True,
                                                                                                                    sort_by_fn=Function.RELATIVE_STRENGTH_INDEX,
                                                                                                                    sort_by_window_days=10,
                                                                                                                    children=[
                                                                                                                        Asset(
                                                                                                                            id="bdd7e4d9-b69b-4a5b-bc9c-106ad7e746c3",
                                                                                                                            step="asset",
                                                                                                                            name="ProShares UltraPro Short QQQ",
                                                                                                                            ticker="SQQQ",
                                                                                                                            exchange="XNAS",
                                                                                                                            price=48.15,
                                                                                                                            dollar_volume=4778684066.25,
                                                                                                                            has_marketcap=False,
                                                                                                                        ),
                                                                                                                        Asset(
                                                                                                                            id="2c99eaaa-9793-4880-aae6-1ee1e3a06060",
                                                                                                                            step="asset",
                                                                                                                            name="Vanguard Short-Term Bond ETF",
                                                                                                                            ticker="BSV",
                                                                                                                            exchange="ARCX",
                                                                                                                            price=76.51,
                                                                                                                            dollar_volume=164303924.33,
                                                                                                                            has_marketcap=False,
                                                                                                                        ),
                                                                                                                    ],
                                                                                                                ),
                                                                                                            ],
                                                                                                        ),
                                                                                                    ],
                                                                                                ),
                                                                                                IfChildFalse(
                                                                                                    id="2061746c-00f0-4941-9f50-68f18a57e05e",
                                                                                                    step="if-child",
                                                                                                    is_else_condition=True,
                                                                                                    children=[
                                                                                                        Asset(
                                                                                                            id="3d3b55d1-7c43-4e81-9bbf-ab2f593512bc",
                                                                                                            step="asset",
                                                                                                            name="ProShares UltraPro QQQ",
                                                                                                            ticker="TQQQ",
                                                                                                            exchange="XNAS",
                                                                                                            price=28.46,
                                                                                                            dollar_volume=4185339154.76,
                                                                                                            has_marketcap=False,
                                                                                                        ),
                                                                                                    ],
                                                                                                ),
                                                                                            ],
                                                                                        ),
                                                                                    ],
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ],
                                                                ),
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
# Backtest
client = ComposerClient(
    api_key=os.getenv("COMPOSER_API_KEY"),
    api_secret=os.getenv("COMPOSER_API_SECRET"),
)

res = client.backtest.run_v2(symphony=symph)
print(res)
